### ISSUE TITLE
Model run in Pecan VM not working

### ISSUE THREAD

**Issue by KristinaRiemer** [PecanProject/pecan#2364]
### Bug Description

After going through all of the pages for inputs to a Pecan run in the VM, the fourth page (http://localhost:6480/pecan/04-runpecan.php) is just blank. 

### To Reproduce

1. Open up VirtualBox app and get Pecan ova running
2. Go to http://localhost:6480/pecan/ in the browser
3. Follow the instructions in the "Hands-On Demo 01" https://pecanproject.github.io/pecan-documentation/develop/pecan-hands-on-demo-01-basic-run.html
4. After hitting "Next" button at end of section 36.2.7.5, putting in AmerifluxLBL info, and hitting "Agree" button, the next page is blank

Alternatively, can try to do an ED2 run with the following inputs: 
```
* Host = pecan.vm
* Model = ED2.2 (git)
* Site Group = All Sites
* Site = EBI Energy farm

* PFTs
   1. ebifarm.c3grass
   2. ebifarm.c4crop
   3. ebifarm.forb
* Start Date = 2004/01/01
* End Date = 2009/12/31
* ED2.cohort = ebifarm.lat40.0long-88.0.css
* ED2.patch = ebifarm.lat40lon-88.0.pss
* ED2.site = ebifarm. lat40.0lon88.0.site
* Ed.met_driver_header = ED_MET_DRIVER_HEADER 2004-2009
* Land use = Earth Land Surface
* Soil = FAO_
* Thermal sums = Earth Land Surface
* Vegetation = OGE2
Check “Edit model config” box
```

## Expected behavior

Expect the next page to show the model run in progress. 

## Screenshots

<img width="1085" alt="Screen Shot 2019-05-28 at 12 34 14 PM" src="https://user-images.githubusercontent.com/6686508/58506768-0a79ed00-8145-11e9-979c-e1fad4e11584.png">

## Machine (please complete the following information):

 - Server: VM
 - OS: macOS 10.13
 - Browser: Firefox (also occurs on Chrome)

**Comment by robkooper** [comment]
I managed to run it fine, can you show the output from `/var/log/apache2/error.log`

**Comment by KristinaRiemer** [comment]
@robkooper where do I find that file?

**Comment by robkooper** [comment]
in the vm, just do a `cat /var/log/apache2/error.log`, you might have to use `sudo cat /var/log/apache2/error.log`

**Comment by KristinaRiemer** [comment]
This is just for today, looks like something with the attributes table? 
```
[Wed May 29 13:04:06.105535 2019] [core:notice] [pid 1062] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 29 13:05:53.985381 2019] [php7:notice] [pid 1078] [client 10.0.2.2:56279] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:05:57.552014 2019] [php7:notice] [pid 1078] [client 10.0.2.2:56279] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:01.414630 2019] [php7:notice] [pid 1078] [client 10.0.2.2:56279] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:19.308165 2019] [php7:notice] [pid 1074] [client 10.0.2.2:56289] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:24.454184 2019] [php7:notice] [pid 4369] [client 10.0.2.2:56290] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:31.812662 2019] [php7:notice] [pid 4370] [client 10.0.2.2:56291] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:07:19.529383 2019] [php7:error] [pid 1076] [client 10.0.2.2:56295] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "attributes" does not exist\nLINE 1: INSERT INTO attributes(container_type, container_id, value) ...\n                    ^ in /home/carya/pecan/web/04-runpecan.php:201\nStack trace:\n#0 /home/carya/pecan/web/04-runpecan.php(201): PDOStatement->execute()\n#1 {main}\n  thrown in /home/carya/pecan/web/04-runpecan.php on line 201, referer: http://localhost:6480/pecan/03a-ameriflux.php
```

**Comment by robkooper** [comment]
you need to migrate the database. You can do this using `docker-compose run --rm bety migrate`.

**Comment by KristinaRiemer** [comment]
I did that from within the VM and restarted it and it didn't work? 

```
[Wed May 29 13:04:06.049216 2019] [mpm_prefork:notice] [pid 1062] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed May 29 13:04:06.105535 2019] [core:notice] [pid 1062] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 29 13:05:53.985381 2019] [php7:notice] [pid 1078] [client 10.0.2.2:56279] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:05:57.552014 2019] [php7:notice] [pid 1078] [client 10.0.2.2:56279] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:01.414630 2019] [php7:notice] [pid 1078] [client 10.0.2.2:56279] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:19.308165 2019] [php7:notice] [pid 1074] [client 10.0.2.2:56289] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:24.454184 2019] [php7:notice] [pid 4369] [client 10.0.2.2:56290] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:06:31.812662 2019] [php7:notice] [pid 4370] [client 10.0.2.2:56291] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 13:07:19.529383 2019] [php7:error] [pid 1076] [client 10.0.2.2:56295] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "attributes" does not exist\nLINE 1: INSERT INTO attributes(container_type, container_id, value) ...\n                    ^ in /home/carya/pecan/web/04-runpecan.php:201\nStack trace:\n#0 /home/carya/pecan/web/04-runpecan.php(201): PDOStatement->execute()\n#1 {main}\n  thrown in /home/carya/pecan/web/04-runpecan.php on line 201, referer: http://localhost:6480/pecan/03a-ameriflux.php
[Wed May 29 14:19:26.465285 2019] [php7:notice] [pid 1077] [client 10.0.2.2:58387] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 14:28:42.704303 2019] [php7:notice] [pid 1075] [client 10.0.2.2:58549] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 14:28:49.577173 2019] [php7:notice] [pid 4369] [client 10.0.2.2:58550] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 14:33:34.696729 2019] [php7:error] [pid 1077] [client 10.0.2.2:58629] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "attributes" does not exist\nLINE 1: INSERT INTO attributes(container_type, container_id, value) ...\n                    ^ in /home/carya/pecan/web/04-runpecan.php:201\nStack trace:\n#0 /home/carya/pecan/web/04-runpecan.php(201): PDOStatement->execute()\n#1 {main}\n  thrown in /home/carya/pecan/web/04-runpecan.php on line 201, referer: http://localhost:6480/pecan/03a-ameriflux.php
[Wed May 29 14:36:45.844609 2019] [mpm_prefork:notice] [pid 959] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Wed May 29 14:36:45.914438 2019] [core:notice] [pid 959] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 29 14:38:14.237809 2019] [php7:notice] [pid 1033] [client 10.0.2.2:58660] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 14:38:24.587609 2019] [php7:notice] [pid 1031] [client 10.0.2.2:58671] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 14:39:52.390545 2019] [php7:notice] [pid 1029] [client 10.0.2.2:58686] PHP Notice:  Undefined index: displayname in /home/carya/pecan/web/hostmodelinfo.php on line 89, referer: http://localhost:6480/pecan/02-modelsite.php
[Wed May 29 14:40:31.656076 2019] [php7:error] [pid 1031] [client 10.0.2.2:58702] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "attributes" does not exist\nLINE 1: INSERT INTO attributes(container_type, container_id, value) ...\n                    ^ in /home/carya/pecan/web/04-runpecan.php:201\nStack trace:\n#0 /home/carya/pecan/web/04-runpecan.php(201): PDOStatement->execute()\n#1 {main}\n  thrown in /home/carya/pecan/web/04-runpecan.php on line 201, referer: http://localhost:6480/pecan/03a-ameriflux.php
```

**Comment by KristinaRiemer** [comment]
Also, is that something I would need to do regularly?

**Comment by robkooper** [comment]
Nope only when there is a new version of BETY and there is a migration.

Looks like the migration did not work. When you ran the migrate were there any messages? When you do a `docker ps` what version of BETY container is running.

**Comment by KristinaRiemer** [comment]
```
carya@pecan:~$ docker-compose run --rm bety migrate
Starting carya_postgres_1 ... done
Migrate database.
```
Under IMAGES, it says the bety container is the latest. I'm assuming that means latest version?

**Comment by robkooper** [comment]
ok, try `docker-compose pull bety` first, then `docker-compose run --rm bety migrate`. Looks like the VM has the older version of the BETY container.

**Comment by robkooper** [comment]
did you do a `git pull` for PEcAn?

**Comment by KristinaRiemer** [comment]
Okay, doing the docker-compose pull first worked! Thanks for your help @robkooper! 

So how often should I do these things to keep the VM up to date?

**Comment by robkooper** [comment]
mostly when there is a new release of BETY, most of the others are ok. That being said you can do a `docker-compose pull` at any time. For my development machine I do it nightly and for the production machine once a week. Both are done using a cronjob `cd /home/carya; docker-compose pull; docker-compose up -d`

**Comment by KristinaRiemer** [comment]
Great, if I start using the VM more frequently maybe I'll implement that.
